services:
  sge.postgres:
    image: postgres:15 # Utilise PostgreSQL 15 pour éviter les problèmes de compatibilité
    container_name: sge_postgres
    environment: # Variables d'environnement pour créer la DB + user
      POSTGRES_DB: sgedb
      POSTGRES_USER: sgeuser
      POSTGRES_PASSWORD: sgepassword
    ports:
      - "5432:5432" # exposer le port pour accès depuis l'hôte (optionnel en dev)
    volumes:
      - postgres_data:/var/lib/postgresql/data # persistance des données
    networks:
      - sge_network

  sge.api:
    image: sge.api
    build:
      context: . # contexte de build (racine solution)
      dockerfile: GestionEmps.API/Dockerfile # chemin vers le Dockerfile du projet API
    container_name: sge_api
    ports:
      - "8005:8080" # mappe le port 8080 du conteneur sur 8005 de l'hôte
    depends_on:
      - sge.postgres # démarre postgres avant l'api (ordre, pas garantie de readiness)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=sge.postgres;Database=sgedb;Username=sgeuser;Password=sgepassword
    networks:
      - sge_network

volumes:
  postgres_data: # Volumes pour persister la BDD (sinon perte des données au redémarrage)

networks:
  sge_network:
    driver: bridge
